### ISSUE TITLE
Many undeclared variables

### ISSUE THREAD

**Issue by aakumykov** [feilipu/Goldilocks_Analogue_DAC_Library#1]
Simple_DAC example sketch compilation fails with bunch on error messages like "error: 'VAR' undeclared".

Library version: 1.0.3
OS: Debian Jessie amd64
Arduino IDE: 1.8.5 amd64

Steps to reproduce:
1) install Goldilocks_Analogue_DAC_Library from IDEs library manager;
2) open Simple_DAC example comed with library;
3) compile sketch in Arduino IDE

**Error log:**

> 
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c: In function 'DAC_init':
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:48:2: error: 'UBRR1' undeclared (first use in this function)
>   UBRR1 = 0x0000;       // Set Baud Rate to maximum, to speed XCK1 setting time.
>   ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:48:2: note: each undeclared identifier is reported only once for each function it appears in
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:51:2: error: 'UCSR1C' undeclared (first use in this function)
>   UCSR1C = _BV(UMSEL11) | _BV(UMSEL10); // Set USART MSPI mode of operation using SPI data mode 0,0. UCPHA1 = UCSZ10
>   ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:51:15: error: 'UMSEL11' undeclared (first use in this function)
>   UCSR1C = _BV(UMSEL11) | _BV(UMSEL10); // Set USART MSPI mode of operation using SPI data mode 0,0. UCPHA1 = UCSZ10
>                ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:51:30: error: 'UMSEL10' undeclared (first use in this function)
>   UCSR1C = _BV(UMSEL11) | _BV(UMSEL10); // Set USART MSPI mode of operation using SPI data mode 0,0. UCPHA1 = UCSZ10
>                               ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:52:2: error: 'UCSR1B' undeclared (first use in this function)
>   UCSR1B = _BV(TXEN1);     // Enable transmitter. Enable the TX1 (don't enable the RX1, and the rest of the interrupt enable bits leave set to 0 too).
>   ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:52:15: error: 'TXEN1' undeclared (first use in this function)
>   UCSR1B = _BV(TXEN1);     // Enable transmitter. Enable the TX1 (don't enable the RX1, and the rest of the interrupt enable bits leave set to 0 too).
>                ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c: In function 'DAC_Timer3_init':
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:84:3: error: 'TIMSK3' undeclared (first use in this function)
>    TIMSK3  = 0x00;     // clear all Timer 3 interrupts.
>    ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:85:3: error: 'TIFR3' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>    ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:85:15: error: 'ICF3' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:85:27: error: 'OCF3B' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                            ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:85:40: error: 'OCF3A' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                                         ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:85:53: error: 'TOV3' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                                                      ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:86:3: error: 'TCCR3A' undeclared (first use in this function)
>    TCCR3A = 0x00;     // set to CTC Mode 12.
>    ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:87:3: error: 'TCCR3B' undeclared (first use in this function)
>    TCCR3B = _BV(WGM33) | _BV(WGM32) | _BV(CS30); // CTC Mode 12. TOP = ICR3. No prescaling.
>    ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:87:16: error: 'WGM33' undeclared (first use in this function)
>    TCCR3B = _BV(WGM33) | _BV(WGM32) | _BV(CS30); // CTC Mode 12. TOP = ICR3. No prescaling.
>                 ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:87:29: error: 'WGM32' undeclared (first use in this function)
>    TCCR3B = _BV(WGM33) | _BV(WGM32) | _BV(CS30); // CTC Mode 12. TOP = ICR3. No prescaling.
>                              ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:87:42: error: 'CS30' undeclared (first use in this function)
>    TCCR3B = _BV(WGM33) | _BV(WGM32) | _BV(CS30); // CTC Mode 12. TOP = ICR3. No prescaling.
>                                           ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:88:3: error: 'TCCR3C' undeclared (first use in this function)
>    TCCR3C = 0x00;     // not used
>    ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:90:3: error: 'TCNT3' undeclared (first use in this function)
>    TCNT3 =  0x0000;    // clear the counter, high byte first for 16bit writes. gcc compiler knows how to handle this.
>    ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:91:3: error: 'ICR3' undeclared (first use in this function)
>    ICR3 = (F_CPU / ((uint32_t)samplesSecond)) -1; // Set ICR3 to be the TOP value.
>    ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:93:15: error: 'ICIE3' undeclared (first use in this function)
>   TIMSK3 = _BV(ICIE3);    // turn on Input Capture interrupt (used for overflow interrupt when ICR3 is TOP.)
>                ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c: In function 'DAC_Timer3_end':
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:101:3: error: 'TIMSK3' undeclared (first use in this function)
>    TIMSK3  = 0x00;               // clear all Timer 3 interrupts.
>    ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:102:3: error: 'TIFR3' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>    ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:102:15: error: 'ICF3' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:102:27: error: 'OCF3B' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                            ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:102:40: error: 'OCF3A' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                                         ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:102:53: error: 'TOV3' undeclared (first use in this function)
>    TIFR3 = _BV(ICF3) | _BV(OCF3B) | _BV(OCF3A) | _BV(TOV3);  // clear all Timer 3 flags.
>                                                      ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c: In function 'DAC_out':
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:148:2: error: 'UCSR1A' undeclared (first use in this function)
>   UCSR1A = _BV(TXC1);     // Clear the Transmit complete flag.
>   ^
> In file included from /home/user/arduino-1.8.5/hardware/tools/avr/avr/include/avr/io.h:99:0,
>                  from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:7:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:148:15: error: 'TXC1' undeclared (first use in this function)
>   UCSR1A = _BV(TXC1);     // Clear the Transmit complete flag.
>                ^
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:150:2: error: 'UDR1' undeclared (first use in this function)
>   UDR1 = write.value.u8[1];   // Begin transmission ch_A.
>   ^
> In file included from /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:8:0:
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c: In function 'TIMER3_CAPT_vect':
> /home/user/Arduino/libraries/Goldilocks_Analogue_DAC_Library/src/DAC.c:188:5: warning: 'TIMER3_CAPT_vect' appears to be a misspelled signal handler, missing __vector prefix [-Wmisspelled-isr]
>  ISR(TIMER3_CAPT_vect)
>      ^
> exit status 1
>

**Comment by feilipu** [comment]
You are trying to use the library with the Arduino Uno (328p), which will not work.
The compilation errors relate to configurations of a serial port and a timer that don't exist on the 328p.

The library is designed to use the Goldilocks Analogue (1284p), or the Arduino Mega (1280, 2560), or which have multiple serial ports.

The library uses the Serial Port 1 to drive the DAC in [MSPIM](https://feilipu.me/2015/02/17/avr-atmega-usart-spi-mspim/) mode, as is configured on the [Goldilocks Analogue](https://www.tindie.com/products/feilipu/goldilocks-analogue/), but this doesn't stop you attaching a [MCP4822 DAC](https://www.microchip.com/wwwproducts/en/MCP4822) to any Arduino Mega and getting the same result.

In the Board Manager, change the board to Arduino Mega and the compile errors disappear.
